### ISSUE TITLE
Fix login page background image to fit the screen

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [tharakanandakumara/sign#1]
Fix login page background image to fit the screen.

**Comment by grlwholifts** [comment]
hi, can I work on this?

**Comment by ShanikaEdiriweera** [comment]
@ruchikabgosain yes sure!

**Comment by grlwholifts** [comment]
thanks @ShanikaEdiriweera. could you let me know which files do I need to edit for the same?

**Comment by grlwholifts** [comment]
hope @KManiKumarReddy you will follow some netiqette before intervening any conversation :)
