### ISSUE TITLE
Add a licence 

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [tharakanandakumara/sign#14]

**Comment by R3l4x3** [comment]
What license were you thinking of?

**Comment by ShanikaEdiriweera** [comment]
@R3l4x3 A licence that would restrict commercial use. And only allow use and modification for non-commercial use.

**Comment by ShanikaEdiriweera** [comment]
@R3l4x3 are you working on this?

**Comment by KManiKumarReddy** [comment]
I suggest https://opensource.org/licenses/GPL-3.0

Others may use it commercially but should reveal the source to whoever they are providing the software.

Others may modify it but can only release under the same Open Source license and maintain updates from the original source i.e. this codebase.

Do you want me to add this license?

**Comment by ShanikaEdiriweera** [comment]
@KManiKumarReddy how about this one -https://creativecommons.org/licenses/by-nc-sa/4.0/ ?
Is this a proper licence?
Is there a more popular one with these conditions?

**Comment by KManiKumarReddy** [comment]
Yes, you may use https://creativecommons.org/licenses/by-nc-sa/4.0/

It is a popular one though not very common in software projects and used mostly for designs.

There are other popular ones similar to what you've mentioned like the GPL-3.0, Apache 2.0, etc. but few of them will require code to be more stringent i.e. all CSS that we import and other libraries we import should also include licence with the code or binary imported.

People generally use MIT or MPL license as they'll not require much emphasis on our code but they are much more open-ended i.e. they'll allow anyone to use your code however they like.

I believe Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) - the one you mentioned itself is better for your scenario.

**Comment by ShanikaEdiriweera** [comment]
@KManiKumarReddy thanks for the explanation. Please go on and add it.
