### ISSUE TITLE
DataTable Warning when loading dashboard

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [tharakanandakumara/sign#22]
DataTables warning: table id=live-attendence - Requested unknown parameter '1' for row 0, column 1. For more information about this error, please see http://datatables.net/tn/4

**Comment by ShanikaEdiriweera** [comment]
Might be the issue - https://datatables.net/forums/discussion/48369/datatables-warning-requested-unknown-parameter-id-for-row-3-column-0

**Comment by bethuxs** [comment]
I can't install the project on local

**Comment by ShanikaEdiriweera** [comment]
@EBethus This is the backend repo - https://github.com/ShanikaEdiriweera/student-attendance-system-backend Try to set it up.

Check the comments here ShanikaEdiriweera/student-attendance-system-backend#1
Have to add config files and run mongodb locally!

Then you can create an admin user for yourself using the /user API endpoint. check the sample request in samples

**Comment by ShanikaEdiriweera** [comment]
Here is the sample request to register a user. You can use Postman.
Use the master key you added when configuring.

// POST http://localhost:3000/public/register
// HEADER Authorization: MASTER <MASTER_KEY>
{
	"name": "John Doe",
	"username": "john",
	"password": "11111",
	"email": "john@gmail.com",
	"contact": "777111222",
	"userType": "admin" // "userType": "user"
}

**Comment by ShanikaEdiriweera** [comment]
@EBethus are you working on this?
