### ISSUE TITLE
ToDate in monthly report requests are always set to 31

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [tharakanandakumara/sign#29]
ToDate in monthly report requests are always set to 31. This should be the correct last date of the month.
This should be fixed in the ajax requests in

-  grade-monthly-report_3.php
- class-monthly-report.php

**Comment by Shinji22** [comment]
Hey, I can have a look at this bug if you want.

**Comment by ShanikaEdiriweera** [comment]
Yes please

--
Shanika Ediriweera
Department of Computer Science and Engineering
University of Moratuwa
