### ISSUE TITLE
Month value in monthly report requests are malformed

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [tharakanandakumara/sign#30]
Month value in monthly report requests are malformed. A '0' is always added to front. This should be the correct 2 digit month.
This should be fixed in the ajax requests in

grade-monthly-report_3.php
class-monthly-report.php

**Comment by Suman321123** [comment]
can I fix this issue?

**Comment by ShanikaEdiriweera** [comment]
Yeah sure

--
Shanika Ediriweera
Department of Computer Science and Engineering
University of Moratuwa
