### ISSUE TITLE
Student update page DOB(datepicker) and Medium(dropdown) is not populating data 

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [tharakanandakumara/sign#9]
Student update form DOB(datepicker) and Medium(dropdown) is not populating data fetched from call.
Data is there from tha API call, the form datepicker and dropdown should show the initial values.

**Comment by bluemorbo** [comment]
Hi - I'd like to look at this. I've cloned the repo down to my local machine and I can get to the login page, but no further.

If you could show me how to finish the setup, I'd be more than happy to submit a PR for the reported issue. Thanks in advance :)

**Comment by ShanikaEdiriweera** [comment]
@bluemorbo great to see you are interested in this project. Here's how to get started.

This is the backend repo - https://github.com/ShanikaEdiriweera/student-attendance-system-backend Try to set it up.

Check the comments here ShanikaEdiriweera/student-attendance-system-backend#1
Have to add config files and run mongodb locally!

Then you can create an admin user for yourself using the /user API endpoint. check the sample request in samples

**Comment by bluemorbo** [comment]
Hey - I've managed to get the backend repo running and connecting to a local instance of mongodb... and that's as far as I can get. I've searched both repos for references to a user endpoint, but I appear to be missing something.

Disclaimer: I'm new to mongodb, but happy to learn something new :)

**Comment by ShanikaEdiriweera** [comment]
@bluemorbo thats great you learned mongodb!

Here is the sample request to register a user. You can use Postman.
Use the master key you added when configuring.

// POST http://localhost:3000/public/register
// HEADER Authorization: MASTER <MASTER_KEY>
{
	"name": "John Doe",
	"username": "john",
	"password": "11111",
	"email": "john@gmail.com",
	"contact": "777111222",
	"userType": "admin" // "userType": "user"
}

**Comment by bluemorbo** [comment]
@ShanikaEdiriweera thanks for this - I'm familiar with Postman, so that did the trick. I was able to create both admin and non-admin users then query them in MongoDB. Last thing that tripped me up (but I managed to resolve), was updating `frontend/properties.js` to point to my local instances rather than an AWS instance.

Think I'm good to go now!

**Comment by ShanikaEdiriweera** [comment]
@bluemorbo could you please fix this page - Student Update - /sign/frontend/update-students.php

**Comment by bluemorbo** [comment]
@ShanikaEdiriweera My PC's been out of action for a few days. Soon as it's back up and running, I'll look at fixing this too. Thanks 👍

**Comment by ShanikaEdiriweera** [comment]
@bluemorbo hey how is the progress on this?

**Comment by ShanikaEdiriweera** [comment]
@bluemorbo good job! thanks for the contribution
